name: Blockera Site Toolkit Checkup

on:
    pull_request:
        types: [opened, synchronize, ready_for_review]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    test_wp_plugin_check:
        name: WordPress (PCP)
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera-site-toolkit' || github.event_name == 'pull_request' }}
        env:
            BLOCKERA_GLOBAL_PACKAGES_TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
            BLOCKERA_PLUGIN_CHECK_ZIP: blockera-site-toolkit.zip
            BLOCKERA_PLUGIN_CHECK_BUILD_DIR: ./build/blockera-site-toolkit
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.BLOCKERABOT_PAT }}

            - name: Ensure global-packages submodule
              uses: ./.github/actions/ensure-global-packages

            - uses: ./packages/global-packages/packages/dev-tools/github/actions/plugin-check
              with:
                  repo-token: ${{ secrets.BLOCKERABOT_PAT }}
                  zip-file: blockera-site-toolkit.zip
                  build-dir: ./build/blockera-site-toolkit
                  php-version: '8.2'
                  composer-options: '--no-dev -o --apcu-autoloader -a'
                  exclude-directories: vendor,.wordpress-org
                  exclude-checks: |
                      textdomain

    test_php_security_check:
        name: PHP Security Check
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'blockeraai/blockera-site-toolkit' || github.event_name == 'pull_request' }}
        env:
            BLOCKERA_GLOBAL_PACKAGES_TOKEN: ${{ secrets.BLOCKERABOT_PAT }}
        steps:
            - uses: actions/checkout@v5
              with:
                  token: ${{ secrets.BLOCKERABOT_PAT }}

            - name: Ensure global-packages submodule
              uses: ./.github/actions/ensure-global-packages

            - uses: ./packages/global-packages/packages/dev-tools/github/actions/php-security-check
